package failureCaseWorking;

import org.testng.Assert;
import org.testng.annotations.Test;

public class TestCaseWarehouse {
	

	@Test(retryAnalyzer=AnalyzerClass.class)
	public void test1() {
		
		System.out.println("TestCase1");
		Assert.fail();
	}
	
	
	@Test
	 public void test2() {
	 
	 System.out.println("TestCase2");
	 
	 }

}
